baseURL = "http://berlin.ccc.de/"
languageCode = "de-de"
title = "Chaos Computer Club Berlin e.V."
theme = "beautifulhugo"

[Params]
  license = "CC-BY"
  subtitle = "Willkommen! Wir sind ein Erfa-Kreis des Chaos Computer Club e.V. und die örtliche Niederlassung des CCC in Berlin."
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  DateForm = "30.12.2006"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
  post = "/post/:year/:month/:day/:title/"

[Author]
  twitter = "clubdiscordia"
  email = "mail@berlin.ccc.de"

[[menu.main]]
  name = "Impressum"
  url = "page/impressum/"
  weight = 500

[[menu.main]]
  name = "News"
  url = "post/"
  weight = 600

[mediaTypes]
[mediaTypes."text/calendar"]
suffix = "ics"

[mediaTypes."application/rss"]
suffix = "rss"

[mediaTypes."application/xml"]
suffix = "xml"


[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"

  [outputFormats.XML]
    isPlainText = true
    mediaType = "application/xml"



[outputs]
section = [ "HTML", "Calendar", "RSS", "XML"]
